//! Generate render modules for every built e2e app (`<apps>/<name>/server/q-ssr-plan.json`,
//! emitted by `e2e/qwik-e2e/native-build.ts`) plus the embedded qwikloader. Apps whose plan
//! hits an unsupported gate are compiled in as an error entry — the homepage shows the reason.

use std::fmt::Write as _;
use std::path::PathBuf;

fn module_ident(app_name: &str) -> String {
	let sanitized: String = app_name
		.chars()
		.map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
		.collect();
	format!("app_{sanitized}")
}

fn generate_app(plan_text: &str) -> Result<(String, String), String> {
	let plan: serde_json::Value =
		serde_json::from_str(plan_text).map_err(|error| format!("invalid plan JSON: {error}"))?;
	let entry = plan["entry"].as_u64().ok_or("plan is missing entry")? as usize;
	let entry_function = qwik_ssr_gen::render_function_name(&plan, entry)?;
	let mut code = String::new();
	let component_count = plan["components"]
		.as_array()
		.ok_or("plan components")?
		.len();
	for index in 0..component_count {
		code.push_str(
			&qwik_ssr_gen::generate_component(&plan, index)
				.map_err(|reason| format!("component {index}: {reason}"))?,
		);
	}
	let module_count = plan["modules"].as_array().ok_or("plan modules")?.len();
	for module_index in 0..module_count {
		code.push_str(
			&qwik_ssr_gen::generate_defs(&plan, module_index)
				.map_err(|reason| format!("defs {module_index}: {reason}"))?,
		);
	}
	Ok((code, entry_function))
}

fn main() {
	let repo_root = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../../../../..");
	let apps_dir = std::env::var("QWIK_APPS_DIR")
		.map(PathBuf::from)
		.unwrap_or_else(|_| repo_root.join("e2e/qwik-e2e/apps"));
	println!("cargo:rerun-if-env-changed=QWIK_APPS_DIR");
	println!("cargo:rerun-if-changed={}", apps_dir.display());

	let loader_path = repo_root.join("packages/qwik/dist/qwikloader.js");
	println!("cargo:rerun-if-changed={}", loader_path.display());
	let loader_raw = std::fs::read_to_string(&loader_path).unwrap_or_else(|error| {
		panic!("cannot read {loader_path:?}: {error} — run pnpm build.core.dev")
	});
	let loader_trimmed = loader_raw.trim();
	let qwik_loader = loader_trimmed
		.strip_suffix(';')
		.unwrap_or(loader_trimmed)
		.to_string();

	let mut app_names: Vec<String> = std::fs::read_dir(&apps_dir)
		.map(|entries| {
			entries
				.filter_map(|entry| entry.ok())
				.filter(|entry| entry.path().is_dir())
				.filter_map(|entry| entry.file_name().into_string().ok())
				.collect()
		})
		.unwrap_or_default();
	app_names.sort();

	let mut code = String::from("// generated by build.rs from <apps>/*/server/q-ssr-plan.json\n");
	let mut registry = String::from(
		"pub struct AppEntry {\n    pub name: &'static str,\n    pub render: Option<fn(&mut qwik_ssr_rt::render::SsrContext, &mut String)>,\n    pub error: Option<&'static str>,\n}\npub static APPS: &[AppEntry] = &[\n",
	);
	for app_name in &app_names {
		let app_dir = apps_dir.join(app_name);
		println!("cargo:rerun-if-changed={}", app_dir.display());
		let server_dir = app_dir.join("server");
		if server_dir.is_dir() {
			println!("cargo:rerun-if-changed={}", server_dir.display());
		}
		let plan_path = server_dir.join("q-ssr-plan.json");
		if !plan_path.is_file() {
			continue;
		}
		println!("cargo:rerun-if-changed={}", plan_path.display());
		let plan_text = std::fs::read_to_string(&plan_path)
			.unwrap_or_else(|error| panic!("cannot read {plan_path:?}: {error}"));
		match generate_app(&plan_text) {
			Ok((app_code, entry_function)) => {
				let ident = module_ident(app_name);
				writeln!(code, "pub mod {ident} {{\n{app_code}}}").unwrap();
				writeln!(
					registry,
					"    AppEntry {{ name: {app_name:?}, render: Some({ident}::{entry_function}), error: None }},"
				)
				.unwrap();
			}
			Err(reason) => {
				writeln!(
					registry,
					"    AppEntry {{ name: {app_name:?}, render: None, error: Some({reason:?}) }},"
				)
				.unwrap();
			}
		}
	}
	registry.push_str("];\n");
	code.push_str(&registry);
	writeln!(code, "pub const QWIK_LOADER: &str = {qwik_loader:?};").unwrap();

	let out_file = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("generated.rs");
	std::fs::write(out_file, code).expect("write generated.rs");
}
