//! Generate the render module for the app plan (`q-ssr-plan.json`) produced by the vite
//! build (`e2e/qwik-e2e/native-build.ts`), plus the embedded qwikloader.

use std::path::PathBuf;

fn main() {
	let repo_root = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../../../../..");
	let default_plan = repo_root.join("e2e/qwik-e2e/apps/native-counter/server/q-ssr-plan.json");
	let plan_path = std::env::var("QWIK_SSR_PLAN")
		.map(PathBuf::from)
		.unwrap_or(default_plan);
	println!("cargo:rerun-if-changed={}", plan_path.display());
	println!("cargo:rerun-if-env-changed=QWIK_SSR_PLAN");

	let loader_path = repo_root.join("packages/qwik/dist/qwikloader.js");
	println!("cargo:rerun-if-changed={}", loader_path.display());
	let loader_raw = std::fs::read_to_string(&loader_path).unwrap_or_else(|error| {
		panic!("cannot read {loader_path:?}: {error} — run pnpm build.core.dev")
	});
	let loader_trimmed = loader_raw.trim();
	let qwik_loader = loader_trimmed
		.strip_suffix(';')
		.unwrap_or(loader_trimmed)
		.to_string();

	let plan: serde_json::Value = serde_json::from_str(
		&std::fs::read_to_string(&plan_path)
			.unwrap_or_else(|error| panic!("cannot read {plan_path:?}: {error} — run pnpm node --require ./scripts/runBefore.ts e2e/qwik-e2e/native-build.ts")),
	)
	.expect("plan is valid JSON");

	let entry = plan["entry"].as_u64().expect("plan entry") as usize;
	let entry_function =
		qwik_ssr_gen::render_function_name(&plan, entry).expect("entry render function");
	let component_count = plan["components"].as_array().expect("components").len();
	let mut code = String::from("// generated by build.rs from q-ssr-plan.json\n");
	for index in 0..component_count {
		code.push_str(
			&qwik_ssr_gen::generate_component(&plan, index)
				.unwrap_or_else(|reason| panic!("component {index}: {reason}")),
		);
	}
	let module_count = plan["modules"].as_array().expect("modules").len();
	for module_index in 0..module_count {
		code.push_str(
			&qwik_ssr_gen::generate_defs(&plan, module_index)
				.unwrap_or_else(|reason| panic!("defs {module_index}: {reason}")),
		);
	}
	code.push_str(&format!(
		"pub use {entry_function} as render_entry;\npub const QWIK_LOADER: &str = {qwik_loader:?};\n"
	));

	let out_file = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("generated.rs");
	std::fs::write(out_file, code).expect("write generated.rs");
}
