packages:
  - 'packages/*'
  - 'e2e/*'
  # - 'starters/adapter/*'
  # - 'starters/features/*'

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - 'esbuild'
  - 'netlify-cli'
  - 'puppeteer'
  - 'sharp'
  - 'simple-git-hooks'
  - 'unix-dgram'
  - 'workerd'

overrides:
  'typescript': '5.4.5'
  'vfile': '6.0.3'

patchedDependencies:
  'density-clustering@1.3.0': 'patches/density-clustering@1.3.0.patch'

engineStrict: true
shellEmulator: true
autoInstallPeers: false
