packages:
  - packages/*
  - e2e/*

autoInstallPeers: false

engineStrict: true

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@rolldown/browser'
  - '@tailwindcss/oxide'
  - esbuild
  - netlify-cli
  - puppeteer
  - sharp
  - simple-git-hooks
  - unix-dgram
  - workerd

overrides:
  typescript: 5.4.5
  vfile: 6.0.3

patchedDependencies:
  density-clustering@1.3.0: patches/density-clustering@1.3.0.patch
  domino@2.1.6: patches/domino@2.1.6.patch

shellEmulator: true
