packages:
  - packages/*
  - e2e/*

autoInstallPeers: false

engineStrict: true

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@rolldown/browser'
  - '@tailwindcss/oxide'
  - esbuild
  - netlify-cli
  - puppeteer
  - sharp
  - simple-git-hooks
  - unix-dgram
  - workerd

overrides:
  '@builder.io/qwik': 'npm:@qwik.dev/core@*'
  '@builder.io/qwik-city': 'npm:@qwik.dev/router'
  'prettier': '3.6.2'
  typescript: 5.8.3
  vfile: 6.0.3

patchedDependencies:
  density-clustering@1.3.0: patches/density-clustering@1.3.0.patch
  domino@2.1.6: patches/domino@2.1.6.patch

shellEmulator: true
