// GENERATED by @gel/generate v0.6.4

import * as $ from "../../reflection";
import * as _ from "../../imports";
import _module__http from "./net/http";
export type $RequestFailureKind = {
  NetworkError: $.$expr_Literal<$RequestFailureKind>;
  Timeout: $.$expr_Literal<$RequestFailureKind>;
} & $.EnumType<"std::net::RequestFailureKind", ["NetworkError", "Timeout"]>;
const RequestFailureKind: $RequestFailureKind = $.makeType<$RequestFailureKind>(
  _.spec,
  "8b93ef2e-2ddd-5ba2-9333-2e28a4d56ede",
  _.syntax.literal,
);

export type $RequestState = {
  Pending: $.$expr_Literal<$RequestState>;
  InProgress: $.$expr_Literal<$RequestState>;
  Completed: $.$expr_Literal<$RequestState>;
  Failed: $.$expr_Literal<$RequestState>;
} & $.EnumType<
  "std::net::RequestState",
  ["Pending", "InProgress", "Completed", "Failed"]
>;
const RequestState: $RequestState = $.makeType<$RequestState>(
  _.spec,
  "5b46c56e-937c-59d2-b3e6-99c31c7c60f0",
  _.syntax.literal,
);

export { RequestFailureKind, RequestState };

type __defaultExports = {
  RequestFailureKind: typeof RequestFailureKind;
  RequestState: typeof RequestState;
  http: typeof _module__http;
};
const __defaultExports: __defaultExports = {
  RequestFailureKind: RequestFailureKind,
  RequestState: RequestState,
  http: _module__http,
};
export default __defaultExports;
