// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | ""
    | "/"
    | "/background.js"
    | "/content-scripts/content.js"
    | "/devtools-hook.js"
    | "/devtools.html"
    | "/icon-128.png"
    | "/icon-16.png"
    | "/icon-32.png"
    | "/icon-48.png"
    | "/inspect-hook.js"
    | "/nav-hook.js"
    | "/panel.html"
    | "/qwikloader.js"
    | "/theme-init.js"
    | "/vnode-bridge.js"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
