//! Layer-A fixture-runner generation (specs/08): run `qwik-ssr-gen` over the linked plan of
//! every native-ready fixture and compile the generated render functions into this crate.
//! The allowlist is explicit — growing it is the visible progress metric, never a silent skip.

use std::fmt::Write as _;
use std::path::PathBuf;

const READY_FIXTURES: &[&str] = &[
	"static-page",
	"signal-counter",
	"mixed-text",
	"child-props",
	"multi-module",
	"store-bind",
	"slot-projection",
	"branch-collection",
	"suspense-inline",
	"template-text",
	"derived-collection",
	"inner-html",
	"visible-task",
	"use-styles",
	"context",
	"static-attrs",
	"suspense-stream",
	"def-helper",
	"class-object",
	"local-component",
	"local-component-captured",
	"local-component-props",
	"local-component-slots",
	"local-component-signal-props",
	"slot-fallback",
	"component-spread-props",
	"local-component-context",
	"component-spread-mixed",
	"component-spread-signal",
	"component-event-prop",
	"cond-attr",
	"plugin-call",
];

fn main() {
	let repo_root = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../../../../..");
	let fixtures_dir = repo_root.join("packages/compiler/conformance/layerA/fixtures");
	println!("cargo:rerun-if-changed={}", fixtures_dir.display());

	// the same minified loader the built JS engine embeds — byte-identical output requires it
	let loader_path = repo_root.join("packages/qwik/dist/qwikloader.js");
	println!("cargo:rerun-if-changed={}", loader_path.display());
	// mirrors scripts/submodule-qwikloader.ts: trim, then drop a single trailing semicolon
	let loader_raw = std::fs::read_to_string(&loader_path).unwrap_or_else(|error| {
		panic!("cannot read {loader_path:?}: {error} — run pnpm build.core.dev")
	});
	let loader_trimmed = loader_raw.trim();
	let qwik_loader = loader_trimmed
		.strip_suffix(';')
		.unwrap_or(loader_trimmed)
		.to_string();

	let mut generated =
		String::from("// generated by build.rs — one module per native-ready Layer-A fixture\n");
	let mut registry = String::new();
	for name in READY_FIXTURES {
		let fixture_dir = fixtures_dir.join(name);
		let plan: serde_json::Value = serde_json::from_str(
			&std::fs::read_to_string(fixture_dir.join("expected/plan.json"))
				.unwrap_or_else(|error| panic!("fixture {name}: cannot read plan: {error}")),
		)
		.expect("plan is valid JSON");
		let request: serde_json::Value = serde_json::from_str(
			&std::fs::read_to_string(fixture_dir.join("request.json")).expect("request.json"),
		)
		.expect("request is valid JSON");

		let entry = plan["entry"].as_u64().expect("plan entry") as usize;
		let entry_function = qwik_ssr_gen::render_function_name(&plan, entry)
			.unwrap_or_else(|reason| panic!("fixture {name}: {reason}"));
		let component_count = plan["components"].as_array().expect("components").len();
		let mut component_code = String::new();
		for index in 0..component_count {
			component_code.push_str(
				&qwik_ssr_gen::generate_component(&plan, index)
					.unwrap_or_else(|reason| panic!("fixture {name}: {reason}")),
			);
		}
		let module_count = plan["modules"].as_array().expect("modules").len();
		for module_index in 0..module_count {
			component_code.push_str(
				&qwik_ssr_gen::generate_defs(&plan, module_index)
					.unwrap_or_else(|reason| panic!("fixture {name}: {reason}")),
			);
		}
		component_code.push_str(
			&qwik_ssr_gen::generate_plugin_fns(&plan, "rust")
				.unwrap_or_else(|reason| panic!("fixture {name}: {reason}")),
		);

		let module_name = name.replace('-', "_");
		let container_tag = request["containerTagName"].as_str().unwrap_or("html");
		let instance_hash = request["instanceHash"].as_str().expect("instanceHash");
		let streaming = request["stream"].as_bool() == Some(true);
		// non-request values mirror the JS conformance harness: dev renderToString defaults
		// with the build-stamped q:version normalized to "conformance"
		writeln!(
			generated,
			"#[allow(non_snake_case, unused_mut, unused_variables, clippy::type_complexity, clippy::comparison_to_empty, clippy::needless_borrow, clippy::needless_else, clippy::borrow_deref_ref)]\npub mod {module_name} {{\n{component_code}\
             pub fn render_page() -> String {{\n    \
                 qwik::render::render_page(\n        \
                     &qwik::render::PageOptions {{\n            \
                         container: qwik::render::ContainerOptions {{\n                \
                             tag: {container_tag:?}.to_string(),\n                \
                             version: \"conformance\".to_string(),\n                \
                             render_mode: \"ssr-dev\".to_string(),\n                \
                             base: \"/build/\".to_string(),\n                \
                             locale: String::new(),\n                \
                             manifest_hash: String::new(),\n                \
                             instance_hash: {instance_hash:?}.to_string(),\n            \
                         }},\n            \
                         qwik_loader: crate::QWIK_LOADER.to_string(),\n            \
	                         chunk_map: None,\n            \
                         streaming: {streaming},\n        \
                     }},\n        \
                     {entry_function},\n    \
                 )\n}}\n}}"
		)
		.unwrap();
		writeln!(
			registry,
			"    ({name:?}, {module_name}::render_page as FixtureRender),"
		)
		.unwrap();
	}
	writeln!(generated, "const QWIK_LOADER: &str = {qwik_loader:?};").unwrap();
	writeln!(
		generated,
		"pub type FixtureRender = fn() -> String;\n\
		 pub const FIXTURES: &[(&str, FixtureRender)] = &[\n{registry}];"
	)
	.unwrap();

	let out_file = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("generated.rs");
	std::fs::write(out_file, generated).expect("write generated.rs");
}
