//! Layer-A fixture-runner generation (specs/08): run `qwik-ssr-gen` over the linked plan of
//! every native-ready fixture and compile the generated render functions into this crate.
//! The allowlist is explicit — growing it is the visible progress metric, never a silent skip.

use std::fmt::Write as _;
use std::path::PathBuf;

const READY_FIXTURES: &[&str] = &["static-page"];

fn main() {
	let fixtures_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
		.join("../../../../../../packages/compiler/conformance/layerA/fixtures");
	println!("cargo:rerun-if-changed={}", fixtures_dir.display());

	let mut generated =
		String::from("// generated by build.rs — one module per native-ready Layer-A fixture\n");
	let mut registry = String::new();
	for name in READY_FIXTURES {
		let fixture_dir = fixtures_dir.join(name);
		let plan: serde_json::Value = serde_json::from_str(
			&std::fs::read_to_string(fixture_dir.join("expected/plan.json"))
				.unwrap_or_else(|error| panic!("fixture {name}: cannot read plan: {error}")),
		)
		.expect("plan is valid JSON");
		let request: serde_json::Value = serde_json::from_str(
			&std::fs::read_to_string(fixture_dir.join("request.json")).expect("request.json"),
		)
		.expect("request is valid JSON");

		let entry = plan["entry"].as_u64().expect("plan entry") as usize;
		let entry_name = plan["components"][entry]["name"]
			.as_str()
			.expect("entry component name")
			.to_lowercase();
		let component_code = qwik_ssr_gen::generate_component(&plan, entry)
			.unwrap_or_else(|reason| panic!("fixture {name}: {reason}"));

		let module_name = name.replace('-', "_");
		let container_tag = request["containerTagName"].as_str().unwrap_or("html");
		let instance_hash = request["instanceHash"].as_str().expect("instanceHash");
		// non-request values mirror the JS conformance harness: dev renderToString defaults
		// with the build-stamped q:version normalized to "conformance"
		writeln!(
			generated,
			"pub mod {module_name} {{\n{component_code}\
             pub fn render_page() -> String {{\n    \
                 qwik_ssr_rt::render::render_container(\n        \
                     &qwik_ssr_rt::render::ContainerOptions {{\n            \
                         tag: {container_tag:?}.to_string(),\n            \
                         version: \"conformance\".to_string(),\n            \
                         render_mode: \"ssr-dev\".to_string(),\n            \
                         base: \"/build/\".to_string(),\n            \
                         locale: String::new(),\n            \
                         manifest_hash: String::new(),\n            \
                         instance_hash: {instance_hash:?}.to_string(),\n        \
                     }},\n        \
                     render_{entry_name},\n    \
                 )\n}}\n}}"
		)
		.unwrap();
		writeln!(
			registry,
			"    ({name:?}, {module_name}::render_page as FixtureRender),"
		)
		.unwrap();
	}
	writeln!(
		generated,
		"pub type FixtureRender = fn() -> String;\n\
		 pub const FIXTURES: &[(&str, FixtureRender)] = &[\n{registry}];"
	)
	.unwrap();

	let out_file = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("generated.rs");
	std::fs::write(out_file, generated).expect("write generated.rs");
}
