// Generated by wxt
/// <reference types="wxt/vite-builder-env" />
import type {} from './types/paths.d.ts';
import type {} from './types/i18n.d.ts';
import type {} from './types/globals.d.ts';
import type {} from './types/imports-module.d.ts';
