//! Layer-0 conformance (specs/08): byte-compare against the goldens generated by the JS
//! engine at `packages/compiler/conformance/layer0/goldens`. The JS side freshness-gates
//! the goldens; this side must match them exactly.

use qwik::coerce::to_ssr_text;
use qwik::escape::escape_html;
use qwik::json::stringify;
use qwik::number::{to_fixed, to_js_string};
use qwik::serdes::{SerdesValue, Serializer};
use qwik::value::{JsObject, Value};
use std::collections::HashMap;
use std::path::PathBuf;
use std::rc::Rc;

fn golden(name: &str) -> serde_json::Value {
	let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
		.join("../../../../../../packages/compiler/conformance/layer0/goldens")
		.join(name);
	let text = std::fs::read_to_string(&path)
		.unwrap_or_else(|error| panic!("cannot read golden {path:?}: {error}"));
	serde_json::from_str(&text).expect("golden is valid JSON")
}

fn f64_from_hex(hex: &str) -> f64 {
	f64::from_bits(u64::from_str_radix(hex, 16).expect("hex bit pattern"))
}

/// Decode the corpora's TaggedValue encoding (serdes-only tags are rejected here).
fn decode_tagged(node: &serde_json::Value) -> Value {
	match node {
		serde_json::Value::Null => Value::Null,
		serde_json::Value::Bool(boolean) => Value::Bool(*boolean),
		serde_json::Value::Number(number) => Value::Number(number.as_f64().expect("f64 number")),
		serde_json::Value::String(text) => Value::String(text.clone()),
		serde_json::Value::Array(items) => Value::Array(items.iter().map(decode_tagged).collect()),
		serde_json::Value::Object(map) => match map.get("$").and_then(|tag| tag.as_str()) {
			Some("undefined") => Value::Undefined,
			Some("nan") => Value::Number(f64::NAN),
			Some("inf") => Value::Number(f64::INFINITY),
			Some("-inf") => Value::Number(f64::NEG_INFINITY),
			Some("-0") => Value::Number(-0.0),
			Some("obj") => {
				let mut object = JsObject::new();
				for pair in map["pairs"].as_array().expect("obj pairs") {
					let pair = pair.as_array().expect("pair");
					object.insert(
						pair[0].as_str().expect("key").to_string(),
						decode_tagged(&pair[1]),
					);
				}
				Value::Object(object)
			}
			Some(tag) => panic!("tag {tag:?} belongs to the serdes corpus"),
			None => {
				// plain JSON object (json-bytes corpus)
				let mut object = JsObject::new();
				for (key, item) in map {
					object.insert(key.clone(), decode_tagged(item));
				}
				Value::Object(object)
			}
		},
	}
}

/// Full TaggedValue decoder for the serdes corpus — `shared` tags decode to the same `Rc`
/// so the serializer observes JS object identity; `set` dedups by SameValueZero.
fn decode_serdes(
	node: &serde_json::Value,
	shared: &mut HashMap<String, Rc<SerdesValue>>,
) -> Rc<SerdesValue> {
	match node {
		serde_json::Value::Null => Rc::new(SerdesValue::Null),
		serde_json::Value::Bool(boolean) => Rc::new(SerdesValue::Bool(*boolean)),
		serde_json::Value::Number(number) => {
			Rc::new(SerdesValue::Number(number.as_f64().expect("f64 number")))
		}
		serde_json::Value::String(text) => Rc::new(SerdesValue::String(text.clone())),
		serde_json::Value::Array(items) => Rc::new(SerdesValue::Array(
			items
				.iter()
				.map(|item| decode_serdes(item, shared))
				.collect(),
		)),
		serde_json::Value::Object(map) => {
			let tag = map
				.get("$")
				.and_then(|tag| tag.as_str())
				.expect("tagged node");
			match tag {
				"undefined" => Rc::new(SerdesValue::Undefined),
				"nan" => Rc::new(SerdesValue::Number(f64::NAN)),
				"inf" => Rc::new(SerdesValue::Number(f64::INFINITY)),
				"-inf" => Rc::new(SerdesValue::Number(f64::NEG_INFINITY)),
				"-0" => Rc::new(SerdesValue::Number(-0.0)),
				"obj" => {
					let mut entries = Vec::new();
					for pair in map["pairs"].as_array().expect("obj pairs") {
						let pair = pair.as_array().expect("pair");
						entries.push((
							pair[0].as_str().expect("key").to_string(),
							decode_serdes(&pair[1], shared),
						));
					}
					Rc::new(SerdesValue::Object(entries))
				}
				"date" => Rc::new(SerdesValue::Date(map["v"].as_f64().expect("date millis"))),
				"url" => Rc::new(SerdesValue::Url(
					map["v"].as_str().expect("url").to_string(),
				)),
				"regex" => Rc::new(SerdesValue::Regex {
					source: map["src"].as_str().expect("regex source").to_string(),
					flags: map["flags"].as_str().expect("regex flags").to_string(),
				}),
				"bigint" => Rc::new(SerdesValue::BigInt(
					map["v"].as_str().expect("bigint digits").to_string(),
				)),
				"map" => {
					let mut entries = Vec::new();
					for pair in map["entries"].as_array().expect("map entries") {
						let pair = pair.as_array().expect("map entry");
						entries.push((
							decode_serdes(&pair[0], shared),
							decode_serdes(&pair[1], shared),
						));
					}
					Rc::new(SerdesValue::Map(entries))
				}
				"set" => {
					let mut items: Vec<Rc<SerdesValue>> = Vec::new();
					for item in map["v"].as_array().expect("set items") {
						let decoded = decode_serdes(item, shared);
						let duplicate =
							items.iter().any(|existing| match (&**existing, &*decoded) {
								(SerdesValue::String(left), SerdesValue::String(right)) => {
									left == right
								}
								(SerdesValue::Number(left), SerdesValue::Number(right)) => {
									left == right || (left.is_nan() && right.is_nan())
								}
								_ => Rc::ptr_eq(existing, &decoded),
							});
						if !duplicate {
							items.push(decoded);
						}
					}
					Rc::new(SerdesValue::Set(items))
				}
				"u8" => Rc::new(SerdesValue::Bytes(
					map["v"]
						.as_array()
						.expect("u8 bytes")
						.iter()
						.map(|byte| byte.as_u64().expect("byte") as u8)
						.collect(),
				)),
				"shared" => {
					if let Some(value) = map.get("v") {
						let decoded = decode_serdes(value, shared);
						shared.insert(map["id"].as_str().expect("shared id").to_string(), decoded);
					}
					Rc::clone(
						shared
							.get(map["id"].as_str().expect("shared id"))
							.expect("shared value defined before use"),
					)
				}
				tag => panic!("unknown serdes tag {tag:?}"),
			}
		}
	}
}

#[test]
fn serdes_state_scripts() {
	for case in golden("serdes.json").as_array().unwrap() {
		let name = case["name"].as_str().unwrap();
		let expected = case["expected"].as_str().unwrap();
		let mut shared = HashMap::new();
		let mut serializer = Serializer::new();
		for root in case["roots"].as_array().unwrap() {
			serializer.add_root(decode_serdes(root, &mut shared));
		}
		assert_eq!(serializer.emit_state_scripts(), expected, "case {name:?}");
	}
}

#[test]
fn numbers_to_string() {
	for entry in golden("numbers.json").as_array().unwrap() {
		let entry = entry.as_array().unwrap();
		let value = f64_from_hex(entry[0].as_str().unwrap());
		let expected = entry[1].as_str().unwrap();
		assert_eq!(to_js_string(value), expected, "bits {}", entry[0]);
	}
}

#[test]
fn numbers_to_fixed() {
	for entry in golden("tofixed.json").as_array().unwrap() {
		let entry = entry.as_array().unwrap();
		let value = f64_from_hex(entry[0].as_str().unwrap());
		let digits = entry[1].as_u64().unwrap() as u32;
		let expected = entry[2].as_str().unwrap();
		assert_eq!(
			to_fixed(value, digits),
			expected,
			"bits {} digits {digits}",
			entry[0]
		);
	}
}

#[test]
fn escape_html_five_chars() {
	for entry in golden("escape.json").as_array().unwrap() {
		let entry = entry.as_array().unwrap();
		let input = entry[0].as_str().unwrap();
		let expected = entry[1].as_str().unwrap();
		assert_eq!(escape_html(input), expected, "input {input:?}");
	}
}

#[test]
fn coerce_to_ssr_text() {
	for case in golden("coerce.json").as_array().unwrap() {
		let value = decode_tagged(&case["input"]);
		let expected = case["expected"].as_str().unwrap();
		assert_eq!(to_ssr_text(&value), expected, "input {:?}", case["input"]);
	}
}

#[test]
fn json_stringify_bytes() {
	for case in golden("json-bytes.json").as_array().unwrap() {
		let expected = case["expected"].as_str().unwrap();
		let value = match case["kind"].as_str().unwrap() {
			"entries" => {
				let mut object = JsObject::new();
				for pair in case["pairs"].as_array().unwrap() {
					let pair = pair.as_array().unwrap();
					object.insert(
						pair[0].as_str().unwrap().to_string(),
						decode_tagged(&pair[1]),
					);
				}
				Value::Object(object)
			}
			"value" => decode_tagged(&case["value"]),
			kind => panic!("unknown json-bytes case kind {kind:?}"),
		};
		assert_eq!(stringify(&value).as_deref(), Some(expected));
	}
}
