import { minimalHtmlResponse } from './error-handler';

const notFounds: [string, string][] = [
  // Will be replaced in post-build with the 404s generated by SSG
  '__QWIK_ROUTER_NOT_FOUND_ARRAY__' as any,
];

/**
 * Return the HTML for a 404 page.
 *
 * @internal
 */
export function getNotFound(prefix: string) {
  // Note that without replacing, this will test _ and return _
  for (const [path, html] of notFounds) {
    if (prefix.startsWith(path)) {
      return html;
    }
  }
  return minimalHtmlResponse(404, 'Resource Not Found');
}
