export enum QwikModule {
  Core = '@qwik.dev/core',
  Spark = '@qwik.dev/core/spark',
}

export enum QwikSymbol {
  ApplyDomProps = 'applyDomProps',
  Captures = '_captures',
  BranchRange = 'BranchRange',
  ForRange = 'ForRange',
  Component = 'component$',
  CreateAttrEffect = 'createAttrEffect',
  CreateAttrExpressionEffect = 'createAttrExpressionEffect',
  CreateBranch = 'createBranch',
  CreateForBlock = 'createForBlock',
  CreateClassEffect = 'createClassEffect',
  CreateComponent = 'createComponent',
  CreateCapturedEvent = 'createCapturedEvent',
  CreateContext = 'createContext',
  CreateContextProvider = 'createContextProvider',
  CreateDomBatchEffect = 'createDomBatchEffect',
  CreatePropsEffect = 'createPropsEffect',
  CreateSsrElementTarget = 'createSsrElementTarget',
  CreateSsrElementTextTarget = 'createSsrElementTextTarget',
  CreateSsrDomBatchEffect = 'createSsrDomBatchEffect',
  CreateSsrRangeTextTarget = 'createSsrRangeTextTarget',
  CreateStyleEffect = 'createStyleEffect',
  CreateTemplate = 'createTemplate',
  CreateTextExpressionEffect = 'createTextExpressionEffect',
  CreateTextNodeEffect = 'createTextNodeEffect',
  EscapeHTML = 'escapeHTML',
  InlinedQrl = 'inlinedQrl',
  MergeProps = 'mergeProps',
  PatchAttrValue = 'patchAttrValue',
  PatchTextValue = 'patchTextValue',
  QrlWithChunk = '_qrlWithChunk',
  ReadTrackedSourceValue = 'readTrackedSourceValue',
  RenderSsrBranch = 'renderSsrBranch',
  RenderSsrForBlock = 'renderSsrForBlock',
  RenderSsrAttrExpression = 'renderSsrAttrExpression',
  RenderSsrProps = 'renderSsrProps',
  RenderSsrAttr = 'renderSsrAttr',
  RenderSsrClass = 'renderSsrClass',
  RenderSsrStyle = 'renderSsrStyle',
  RenderSsrTextExpression = 'renderSsrTextExpression',
  RenderSsrTextNode = 'renderSsrTextNode',
  RunDomBatchEffect = 'runDomBatchEffect',
  SerializeAttrExpressionValue = 'serializeAttrExpressionValue',
  SetEvent = 'setEvent',
  WithCaptures = '_withCaptures',
}
