import type { StaticGenerateRenderOptions } from '@builder.io/qwik-city/static';
import { type ServerAdapterOptions, viteAdapter } from '../../shared/vite';
import fs from 'node:fs';
import { join, relative } from 'node:path';
import { normalizePathSlash } from '../../../utils/fs';

/** @public */
export function fastlyAdapter(opts: FastlyAdapterOptions = {}): any {
  const env = process?.env;
  return viteAdapter({
    name: 'fastly',
    origin: env?.FASTLY_URL ?? env?.ORIGIN ?? 'https://example.edgecompute.app',
    ssg: opts.ssg,
    staticPaths: opts.staticPaths,
    cleanStaticGenerated: true,

    config() {
      return {
        resolve: {
          conditions: ['webworker', 'worker'],
        },
        ssr: {
          target: 'webworker',
          noExternal: true,
        },
        build: {
          ssr: true,
          rollupOptions: {
            output: {
              format: 'es',
              hoistTransitiveImports: false,
              // Ignore Fastly virtual modules
              external: [/fastly:.*/],
            },
          },
        },
        publicDir: false,
      };
    },

    async generate({ clientOutDir, serverOutDir, basePathname }) {
      const computeMjsPath = join(clientOutDir, 'index.mjs');
      const hasComputeMjs = fs.existsSync(computeMjsPath);
      if (!hasComputeMjs) {
        const importPath = relative(clientOutDir, join(serverOutDir, 'entry.fastly'));
        await fs.promises.writeFile(
          computeMjsPath,
          [
            `// generated by @qwik-city/adapters/fastly`,
            `import { fetch } from "${normalizePathSlash(importPath)}";`,
            `// inject special static file server to handle publishing assets as bundled wasm or upload to KV Store`,
            `import { getServer } from "../src/statics.js";`,
            `const staticContentServer = getServer();`,
            `addEventListener('fetch', (event) => event.respondWith(fetch(event, staticContentServer)));`,
          ].join('\n')
        );
      }
    },
  });
}

/** @public */
export interface FastlyAdapterOptions extends ServerAdapterOptions {
  /**
   * Manually add pathnames that should be treated as static paths and not SSR. For example, when
   * these pathnames are requested, their response should come from a static file, rather than a
   * server-side rendered response.
   */
  staticPaths?: string[];
}

/** @public */
export type { StaticGenerateRenderOptions };
