CREATE TABLE `routes` (
	`id` integer PRIMARY KEY NOT NULL,
	`public_api_key` text,
	`manifest_hash` text NOT NULL,
	`route` text NOT NULL,
	`symbol` text NOT NULL,
	`timeline_00` integer NOT NULL,
	`timeline_01` integer NOT NULL,
	`timeline_02` integer NOT NULL,
	`timeline_03` integer NOT NULL,
	`timeline_04` integer NOT NULL,
	`timeline_05` integer NOT NULL,
	`timeline_06` integer NOT NULL,
	`timeline_07` integer NOT NULL,
	`timeline_08` integer NOT NULL,
	`timeline_09` integer NOT NULL,
	`timeline_10` integer NOT NULL,
	`timeline_11` integer NOT NULL,
	`timeline_12` integer NOT NULL,
	`timeline_13` integer NOT NULL,
	`timeline_14` integer NOT NULL,
	`timeline_15` integer NOT NULL,
	`timeline_16` integer NOT NULL,
	`timeline_17` integer NOT NULL,
	`timeline_18` integer NOT NULL,
	`timeline_19` integer NOT NULL,
	`timeline_20` integer NOT NULL,
	`timeline_21` integer NOT NULL,
	`timeline_22` integer NOT NULL,
	`timeline_23` integer NOT NULL,
	`timeline_24` integer NOT NULL,
	`timeline_25` integer NOT NULL,
	`timeline_26` integer NOT NULL,
	`timeline_27` integer NOT NULL,
	`timeline_28` integer NOT NULL,
	`timeline_29` integer NOT NULL,
	`timeline_30` integer NOT NULL,
	`timeline_31` integer NOT NULL,
	`timeline_32` integer NOT NULL,
	`timeline_33` integer NOT NULL,
	`timeline_34` integer NOT NULL,
	`timeline_35` integer NOT NULL,
	`timeline_36` integer NOT NULL,
	`timeline_37` integer NOT NULL,
	`timeline_38` integer NOT NULL,
	`timeline_39` integer NOT NULL,
	`timeline_40` integer NOT NULL,
	`timeline_41` integer NOT NULL,
	`timeline_42` integer NOT NULL,
	`timeline_43` integer NOT NULL,
	`timeline_44` integer NOT NULL,
	`timeline_45` integer NOT NULL,
	`timeline_46` integer NOT NULL,
	`timeline_47` integer NOT NULL,
	`timeline_48` integer NOT NULL,
	`timeline_49` integer NOT NULL,
	FOREIGN KEY (`public_api_key`) REFERENCES `applications`(`public_api_key`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE UNIQUE INDEX `routeIndex_Symbol` ON `routes` (`public_api_key`,`manifest_hash`,`route`,`symbol`);