service: qwik-lambda-app
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-1
  memorySize: 128
  timeout: 10
  stage: dev

functions:
  qwik:
    handler: server/entry_aws-lambda.qwikApp
    events:
      - httpApi: "*"

custom:
  serverless-offline:
    httpPort: 4000
  serverless-http:
    # Make sure serverless-http serves files correctly
    binary:
      contentTypes:
        - "application/javascript"
        - "text/javascript"
        - "application/json"
        - "text/html"
        - "text/css"
        - "image/*"
        - "font/*"
    # the js files under build have hash names and are immutable
    cacheControl:
      - pattern: "build/**/*.js"
        value: "public, max-age=31536000, immutable"

package:
  excludeDevDependencies: true
  patterns:
    - "!*"
    - "!*/**"
    - "server/**"
    - "dist/**"

plugins:
  - serverless-offline
