import { isBrowser } from '@qwik.dev/core';
import { getServingRouterConfig } from '../../middleware/request-handler/async-request-store';
import type { QwikRouterConfig, RouteData } from './types';

type RouterConfigHolder = {
  config?: QwikRouterConfig;
  /** Resolves once the config is known and its `server$` modules are registered. */
  ready?: Promise<QwikRouterConfig>;
};

// Per bundle, like the platform: one process may serve several apps, each with its own config.
const holder: RouterConfigHolder = {};

/** The config this router copy holds, else the one of the app serving the current request. */
const findRouterConfig = (): QwikRouterConfig | undefined =>
  holder.config ?? getServingRouterConfig();

/**
 * Registers the app's route config with the router copy bundled into the app. The generated
 * `@qwik-router-config` module calls this on the server; the client loads that module lazily
 * instead, since it is a separate chunk.
 *
 * @internal
 */
export const _setRouterConfig = (config: QwikRouterConfig): void => {
  holder.config = config;
  holder.ready = undefined;
};

/**
 * The app's route config: the route trie, server plugins and build options that the Qwik Router
 * Vite plugin generated. Resolves once the config is loaded and its `server$` modules are
 * registered. On the server, the router copy of a Qwik library kept external reads the config of
 * the app serving the current request.
 *
 * @public
 */
export const getRouterConfig = (): Promise<QwikRouterConfig> => {
  const servingConfig = !holder.config && getServingRouterConfig();
  if (servingConfig) {
    // The app's router copy already registered its `server$` modules.
    return Promise.resolve(servingConfig);
  }
  if (!holder.ready) {
    holder.ready = importRouterConfig().catch((error) => {
      // Let the next call try again, e.g. after a failed chunk load.
      holder.ready = undefined;
      throw error;
    });
  }
  return holder.ready;
};

export const loadRouterConfig = getRouterConfig;

const importRouterConfig = async (): Promise<QwikRouterConfig> => {
  if (!holder.config) {
    // The server entry normally registers the config already; only the app build resolves it.
    const configModule = await import('@qwik-router-config').catch((error) => {
      throw isBrowser
        ? error
        : new Error(
            'Qwik Router config not found. Import "@qwik-router-config" in the server entry that the Qwik Router Vite plugin builds.',
            { cause: error }
          );
    });
    // On the server the module registers its config while it loads.
    holder.config ??= configModule as unknown as QwikRouterConfig;
  }
  await holder.config.importEagerModules?.();
  return holder.config;
};

/**
 * The route trie of the app, as generated by the Qwik Router Vite plugin.
 *
 * @public
 */
export const getRoutes = async (): Promise<RouteData> => (await getRouterConfig()).routes;

/**
 * The base pathname the app is served under, such as `/` or `/docs/`.
 *
 * @public
 */
export const getBasePathname = (): string =>
  findRouterConfig()?.basePathname ?? globalThis.__QWIK_ROUTER_BASE_PATHNAME__ ?? '/';

/**
 * Whether the app's URLs end with a trailing slash.
 *
 * @public
 */
export const getTrailingSlash = (): boolean =>
  findRouterConfig()?.trailingSlash ?? !globalThis.__NO_TRAILING_SLASH__;

/** @internal */
export const _getServiceWorkerUrl = (): string | undefined => findRouterConfig()?.serviceWorkerUrl;
