import { isBrowser } from '@qwik.dev/core';
import type { QwikRouterConfig, RouteData } from './types';

type RouterConfigHolder = {
  config?: QwikRouterConfig;
  /** Resolves once the config is known and its `server$` modules are registered. */
  ready?: Promise<QwikRouterConfig>;
};

// Per bundle, like the platform: one process may serve several apps, each with its own config.
const holder: RouterConfigHolder = {};

/**
 * Registers the app's route config with the router copy bundled into the app. The generated
 * `@qwik-router-config` module calls this on the server; the client loads that module lazily
 * instead, since it is a separate chunk.
 *
 * @internal
 */
export const _setRouterConfig = (config: QwikRouterConfig): void => {
  holder.config = config;
  holder.ready = undefined;
};

/**
 * The app's route config: the route trie, server plugins and build options that the Qwik Router
 * Vite plugin generated. Resolves once the config is loaded and its `server$` modules are
 * registered. Only the router copy bundled into the app holds it on the server.
 *
 * @public
 */
export const getRouterConfig = (): Promise<QwikRouterConfig> => {
  if (!holder.ready) {
    holder.ready = loadRouterConfig();
  }
  return holder.ready;
};

const loadRouterConfig = async (): Promise<QwikRouterConfig> => {
  if (!holder.config) {
    if (!isBrowser) {
      throw new Error(
        'Qwik Router config not found. Make sure the server entry is built with the Qwik Router Vite plugin.'
      );
    }
    // The client config is a lazily loaded chunk that only the app build resolves.
    holder.config = (await import('@qwik-router-config')) as unknown as QwikRouterConfig;
  }
  await holder.config.importEagerModules?.();
  return holder.config;
};

/**
 * The route trie of the app, as generated by the Qwik Router Vite plugin.
 *
 * @public
 */
export const getRoutes = async (): Promise<RouteData> => (await getRouterConfig()).routes;

/**
 * The base pathname the app is served under, such as `/` or `/docs/`.
 *
 * @public
 */
export const getBasePathname = (): string =>
  holder.config?.basePathname ?? globalThis.__QWIK_ROUTER_BASE_PATHNAME__ ?? '/';

/**
 * Whether the app's URLs end with a trailing slash.
 *
 * @public
 */
export const getTrailingSlash = (): boolean =>
  holder.config?.trailingSlash ?? !globalThis.__NO_TRAILING_SLASH__;

/** @internal */
export const _getServiceWorkerUrl = (): string | undefined => holder.config?.serviceWorkerUrl;
