// GENERATED by @gel/generate v0.6.4

import type { Executor } from "gel";

export type GetAllUsersReturns = Array<{
  id: string;
  name: string;
  email: string | null;
  has_profile: boolean | null;
  last_updated: Date | null;
}>;

export function getAllUsers(client: Executor): Promise<GetAllUsersReturns> {
  return client.query(`\
select User { **
}`);
}
