// GENERATED by @gel/generate v0.6.4

import type { Executor } from "gel";

export type InsertUserArgs = {
  readonly email: string;
  readonly has_profile: boolean;
  readonly name: string;
};

export type InsertUserReturns = {
  name: string;
  email: string | null;
  has_profile: boolean | null;
} | null;

export function insertUser(
  client: Executor,
  args: InsertUserArgs,
): Promise<InsertUserReturns> {
  return client.querySingle(
    `\
select 
    (
    insert User {
      name := <str>$name,
      email := <str>$email,
      has_profile := <bool>$has_profile,
    }
    unless conflict on .email
  )
  {
    name,
    email,
    has_profile
  }`,
    args,
  );
}
