name: Release

on:
  workflow_run:
    workflows: ['Qwik CI']
    branches: [main]
    types:
      - completed

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success'}}
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20.x
          cache: 'pnpm'
          registry-url: https://registry.npmjs.org/

      - name: Install NPM Dependencies
        run: |
          # Ensure that the qwik binary gets made
          mkdir -p packages/qwik/dist/bindings/
          pnpm install --frozen-lockfile

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
