//! Layer-0 conformance (specs/08): byte-compare against the goldens generated by the JS
//! engine at `packages/compiler/conformance/layer0/goldens`. The JS side freshness-gates
//! the goldens; this side must match them exactly.

use qwik_ssr_rt::coerce::to_ssr_text;
use qwik_ssr_rt::escape::escape_html;
use qwik_ssr_rt::json::stringify;
use qwik_ssr_rt::number::{to_fixed, to_js_string};
use qwik_ssr_rt::value::{JsObject, Value};
use std::path::PathBuf;

fn golden(name: &str) -> serde_json::Value {
	let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
		.join("../../../../../../packages/compiler/conformance/layer0/goldens")
		.join(name);
	let text = std::fs::read_to_string(&path)
		.unwrap_or_else(|error| panic!("cannot read golden {path:?}: {error}"));
	serde_json::from_str(&text).expect("golden is valid JSON")
}

fn f64_from_hex(hex: &str) -> f64 {
	f64::from_bits(u64::from_str_radix(hex, 16).expect("hex bit pattern"))
}

/// Decode the corpora's TaggedValue encoding (serdes-only tags are rejected here).
fn decode_tagged(node: &serde_json::Value) -> Value {
	match node {
		serde_json::Value::Null => Value::Null,
		serde_json::Value::Bool(boolean) => Value::Bool(*boolean),
		serde_json::Value::Number(number) => Value::Number(number.as_f64().expect("f64 number")),
		serde_json::Value::String(text) => Value::String(text.clone()),
		serde_json::Value::Array(items) => Value::Array(items.iter().map(decode_tagged).collect()),
		serde_json::Value::Object(map) => match map.get("$").and_then(|tag| tag.as_str()) {
			Some("undefined") => Value::Undefined,
			Some("nan") => Value::Number(f64::NAN),
			Some("inf") => Value::Number(f64::INFINITY),
			Some("-inf") => Value::Number(f64::NEG_INFINITY),
			Some("-0") => Value::Number(-0.0),
			Some("obj") => {
				let mut object = JsObject::new();
				for pair in map["pairs"].as_array().expect("obj pairs") {
					let pair = pair.as_array().expect("pair");
					object.insert(
						pair[0].as_str().expect("key").to_string(),
						decode_tagged(&pair[1]),
					);
				}
				Value::Object(object)
			}
			Some(tag) => panic!("tag {tag:?} belongs to the serdes corpus"),
			None => {
				// plain JSON object (json-bytes corpus)
				let mut object = JsObject::new();
				for (key, item) in map {
					object.insert(key.clone(), decode_tagged(item));
				}
				Value::Object(object)
			}
		},
	}
}

#[test]
fn numbers_to_string() {
	for entry in golden("numbers.json").as_array().unwrap() {
		let entry = entry.as_array().unwrap();
		let value = f64_from_hex(entry[0].as_str().unwrap());
		let expected = entry[1].as_str().unwrap();
		assert_eq!(to_js_string(value), expected, "bits {}", entry[0]);
	}
}

#[test]
fn numbers_to_fixed() {
	for entry in golden("tofixed.json").as_array().unwrap() {
		let entry = entry.as_array().unwrap();
		let value = f64_from_hex(entry[0].as_str().unwrap());
		let digits = entry[1].as_u64().unwrap() as u32;
		let expected = entry[2].as_str().unwrap();
		assert_eq!(
			to_fixed(value, digits),
			expected,
			"bits {} digits {digits}",
			entry[0]
		);
	}
}

#[test]
fn escape_html_five_chars() {
	for entry in golden("escape.json").as_array().unwrap() {
		let entry = entry.as_array().unwrap();
		let input = entry[0].as_str().unwrap();
		let expected = entry[1].as_str().unwrap();
		assert_eq!(escape_html(input), expected, "input {input:?}");
	}
}

#[test]
fn coerce_to_ssr_text() {
	for case in golden("coerce.json").as_array().unwrap() {
		let value = decode_tagged(&case["input"]);
		let expected = case["expected"].as_str().unwrap();
		assert_eq!(to_ssr_text(&value), expected, "input {:?}", case["input"]);
	}
}

#[test]
fn json_stringify_bytes() {
	for case in golden("json-bytes.json").as_array().unwrap() {
		let expected = case["expected"].as_str().unwrap();
		let value = match case["kind"].as_str().unwrap() {
			"entries" => {
				let mut object = JsObject::new();
				for pair in case["pairs"].as_array().unwrap() {
					let pair = pair.as_array().unwrap();
					object.insert(
						pair[0].as_str().unwrap().to_string(),
						decode_tagged(&pair[1]),
					);
				}
				Value::Object(object)
			}
			"value" => decode_tagged(&case["value"]),
			kind => panic!("unknown json-bytes case kind {kind:?}"),
		};
		assert_eq!(stringify(&value).as_deref(), Some(expected));
	}
}
